version: '3.8'

services:
  db:
    container_name: tusk-local-db
    build:
      context: ./infrastructure/build-context
    volumes:
      - ./infrastructure/volume-mounts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
